import '../styles/globals.css'
import type { AppProps } from 'next/app'
import {Head} from "next/document";

function MyApp({ Component, pageProps }: AppProps) {
  return  <>
    <Head>
      <title> React Projects</title>
      <link rel="stylesheet" href="/styles/reset.css" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    </>
}

export default MyApp
